version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    # Используем env_file для загрузки .env файла
    env_file:
      - .env
    # Дополнительные переменные окружения
    environment:
      - DEBUG=${DEBUG:-false}
      - PORT=${PORT:-8000}
      - HOST=${HOST:-0.0.0.0}
    volumes:
      - ./logs:/app/logs
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # PostgreSQL for persistent data (optional)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=8pilot
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
