version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - PORT=8000
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://n8n_user:n8n_password@postgres:5432/n8n_copilot
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - N8N_DEFAULT_URL=${N8N_DEFAULT_URL}
      - N8N_DEFAULT_API_KEY=${N8N_DEFAULT_API_KEY}
    volumes:
      - ./logs:/app/logs
      - .:/app
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # PostgreSQL for persistent data (optional)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=n8n_copilot
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
